def set_draft(roster_dict):
    roster_dict['transactions'].append({
    'to':'active'
    ,'from':'available'
    ,'player_names':[
         ('Machado','Manny')
        ,('Bieber','Shane')
        ,('Fried','Max')
        ,('Darvish','Yu')
        ,('Franco','Wander')
        ,('Castellanos','Nick')
        ,('Reynolds','Bryan')
        ,('Bautista','Felix')
        ,('Wright','Kyle')
        ,('Bryant','Kris')
        ,('Lynn','Lance')
        ,('Rizzo','Anthony')
        ,('Leclerc','Jose')
        ,('Dominguez','Seranthony')
        ,('Phillips','Evan')
        ,('Suzuki','Seiya')
        ,('Hayes','Ke\'Bryan')
        ,('Paredes','Isaac')
        ,('Kluber','Corey')
        ,('Steele','Justin')
        ,('Kopech','Michael')
        ,('Montas','Frankie')
        ]
    ,'tdesc':'Acquired'
    ,'ttype':'Draft'
    ,'tdate':'2023-03-23'
    ,'t_id':0
    })
    return roster_dict
